### PR TITLE
Initial contribution guidelines

### LINKED ISSUE #297: CONTRIBUTING file
I've noticed that there occasionally are larger pull requests coming in without any issue associated with them. [Some](#296) of [them](#279) are rather large. Would it make sense to create an `CONTRIBUTING` file that asks people to changes before starting to code? Just an idea...

### PR DESCRIPTION
**Pull request by JensRantil**
Occasionally there has been larger pull requests being submitted on
Github without any discussion whatsoever in issues. Feels like a waste
of time when the PRs are closed because they are outside of the project
scope.

This fixes #297.

### CODE REVIEW

**Comment by JensRantil** [comment]
@kr Follow up on a couple of points you made in your [#297 comment](https://github.com/kr/beanstalkd/issues/297#issuecomment-204847771):

> I am not such a huge fan of the all-caps shouting style though, heh

I concur, however using a different filename won't make Github add the [magic header](https://github.com/blog/1184-contributing-guidelines) when submitting a new PR or issue :-/

> It's totally fine with me if people want to open a pull request without also opening an issue, as long as the change makes sense and is an improvement, etc.

I agree. Let's not overengineer a process here. My point is mostly, for everyone to save some time, recommend discussing a larger change than submitting a pile of code. This pull request recommends opening an issue "Before submitting a giant pull request [...]".

**Comment by JensRantil** [comment]
@kr @sergeyklay Any missing bullets in the document?

**Comment by sergeyklay** [comment]
I agree :+1:

**Comment by kr** [comment]
Thanks a bunch for working on this. I went ahead and wrote up an alternative because there were certain things I wanted it to say.

**Comment by JensRantil** [comment]
> I went ahead and wrote up an alternative because there were certain things I wanted it to say.

:+1: Your text was much better. FYI, if you are swamped (we all are, right? ;)) you could have asked me to have written the document. That said, you did an excellent job!

**Pull request closed without merging**
