### PR TITLE
CLI/usability: wal => write-ahead log

### PR DESCRIPTION
**Pull request by JensRantil**
Many users might not know what "WAL" stands for. This will make it more
explicit.

### CODE REVIEW

**Comment by kr** [comment]
:+1:

**Comment by JensRantil** [comment]
Would you like me to submit this to a different branch? Or of this good to be merged?

**Comment by JensRantil** [comment]
> Would you like me to submit this to a different branch? Or of this good to be merged?

@kr Ping.

**Comment by JensRantil** [comment]
@kr If you are going to merge PRs this weeked, here's another candidate.

**Pull request merged**
